2021.11.06: * changed: .github/workflows/tacklebar-totalcmd-download-stats.yml: print warning/error into github workflow from the inner script
git-svn-id: svn+ssh://svn.code.sf.net/p/tacklebar/tacklebar/trunk@306 b6e1d463-c974-416b-a8a8-9e453b4b0c2d

diff --git a/.github/workflows/tacklebar-totalcmd-download-stats.yml b/.github/workflows/tacklebar-totalcmd-download-stats.yml
--- a/.github/workflows/tacklebar-totalcmd-download-stats.yml
+++ b/.github/workflows/tacklebar-totalcmd-download-stats.yml
@@ -18,6 +18,12 @@ jobs:
       - name: allocate directories
         run: |
           mkdir $GITHUB_WORKSPACE/gh-workflow $GITHUB_WORKSPACE/totalcmd-stats
+          echo "WORKFLOW_TEMPDIR=$(mktemp -d)" >> $GITHUB_ENV
+
+      - name: allocate variables
+        run: |
+          echo "write_error_to_file=$WORKFLOW_TEMPDIR/err.log" >> $GITHUB_ENV
+          echo "write_warning_to_file=$WORKFLOW_TEMPDIR/warn.log" >> $GITHUB_ENV
 
       - name: checkout gh-workflow
         uses: actions/checkout@v2
@@ -33,11 +39,33 @@ jobs:
           token: ${{ secrets.SECRET_TOKEN }}
 
       - name: request traffic downloads json
+        id: extract-plugin-downloads
         shell: bash
+        continue-on-error: true
         run: |
           cd $GITHUB_WORKSPACE/totalcmd-stats
           chmod ug+x $GITHUB_WORKSPACE/gh-workflow/bash/totalcmd/extract-plugin-downloads.sh
           $GITHUB_WORKSPACE/gh-workflow/bash/totalcmd/extract-plugin-downloads.sh
+          # caution: no operation after that line if non zero exit code happens above
+
+      - name: allocate error and warning variables
+        if: steps.extract-plugin-downloads.outcome != 'success'
+        run: |
+          # allocate variables here to make it visible in the next step
+          [[ -f "$write_error_to_file" ]] && echo "error_string<<EOF" >> $GITHUB_ENV
+          [[ -f "$write_error_to_file" ]] && cat "$write_error_to_file" >> $GITHUB_ENV
+          [[ -f "$write_error_to_file" ]] && echo "EOF" >> $GITHUB_ENV
+          [[ -f "$write_warning_to_file" ]] && echo "warning_string<<EOF" >> $GITHUB_ENV
+          [[ -f "$write_warning_to_file" ]] && cat "$write_warning_to_file" >> $GITHUB_ENV
+          [[ -f "$write_warning_to_file" ]] && echo "EOF" >> $GITHUB_ENV
+          exit 0
+
+      - name: print errors and warnings
+        if: steps.extract-plugin-downloads.outcome != 'success'
+        run: |
+          [[ -n "$error_string" ]] && echo "::error ::$error_string"
+          [[ -n "$warning_string" ]] && echo "::warning ::$warning_string"
+          exit 255
 
       - name: commit totalcmd-stats
         run: |
